spring.application.name=demo_6
spring.main.banner-mode=off
logging.level.org.springframework=ERROR

# Database Properties
spring.datasource.url=${CONNECTION_STRING_POSTGRESQL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# App Properties
# Cookie
remember.me.key=${REMEMBER_ME_KEY}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#  TODO - CHECK: DISABLING FOR PRODUCTION
logging.level.org.springframework.boot.autoconfigure.security=INFO