spring.application.name=demo_4

# ===============================
# R2DBC (Reactive access)
# ===============================
spring.r2dbc.url=r2dbc:postgresql://localhost:5050/my_webflux
spring.r2dbc.username=postgres
spring.r2dbc.password=12345

# ===============================
# Flyway (JDBC migrations)
# ===============================
spring.flyway.url=jdbc:postgresql://localhost:5050/my_webflux
spring.flyway.user=postgres
spring.flyway.password=12345

# Optional: location of migration scripts (default:classpath:db/migration)
spring.flyway.locations=classpath:db/migration
